#!/bin/bash
# The real script
if [ $# -lt 4 ]; then
	# Something's wrong, bail
	cat >&2 <<-EOF
	Usage: git submodule foreach '$PWD/$0 "\$name" "\$path" "\$sha1" "\$toplevel"'
	EOF
	exit 1
fi

parent_root="$4"
sm_name="$1"
sm_relative_root="$2"

modules_file="$parent_root/.gitmodules"
git_config_submodules() {
	git config --file "$modules_file" "$@"
}

url_origin="$(git_config_submodules submodule."$sm_name".url)"
url_upstream="$(git_config_submodules submodule."$sm_name".url-upstream)"
branch_current="$(git rev-parse HEAD)"
branch_master="$(git rev-parse master)"
if [ -z "$url_upstream" ]; then
	# This has no upstream, skip
	exit 0
fi

git remote remove upstream
git remote add upstream "$url_upstream"
git config --local branch.master.pushremote origin
git fetch --all --quiet || true # Ignore errors
